//proto file for storing messages used by storage.go

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/proto/record.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_internal_proto_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_internal_proto_record_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Record) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_internal_proto_record_proto protoreflect.FileDescriptor

const file_internal_proto_record_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/record.proto\x12\x06record\"@\n" +
	"\x06Record\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayloadB\x18Z\x16./internal/proto;protob\x06proto3"

var (
	file_internal_proto_record_proto_rawDescOnce sync.Once
	file_internal_proto_record_proto_rawDescData []byte
)

func file_internal_proto_record_proto_rawDescGZIP() []byte {
	file_internal_proto_record_proto_rawDescOnce.Do(func() {
		file_internal_proto_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_record_proto_rawDesc), len(file_internal_proto_record_proto_rawDesc)))
	})
	return file_internal_proto_record_proto_rawDescData
}

var file_internal_proto_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_record_proto_goTypes = []any{
	(*Record)(nil), // 0: record.Record
}
var file_internal_proto_record_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_record_proto_init() }
func file_internal_proto_record_proto_init() {
	if File_internal_proto_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_record_proto_rawDesc), len(file_internal_proto_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_record_proto_goTypes,
		DependencyIndexes: file_internal_proto_record_proto_depIdxs,
		MessageInfos:      file_internal_proto_record_proto_msgTypes,
	}.Build()
	File_internal_proto_record_proto = out.File
	file_internal_proto_record_proto_goTypes = nil
	file_internal_proto_record_proto_depIdxs = nil
}
