Port: 8080
Host: "localhost"
Topics:
  - "mytopic"
  - "anothertopic"
Persistence:
  Enabled: false 
  Directory: "broker/data/topics/"
Tls:
  Enabled: true 
  CertFile: "broker/data/tls/server.crt"
  KeyFile: "broker/data/tls/server.key"
  
